# config/webpacker.yml

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  compile: true # 開発環境で自動コンパイルを有効にする

  # 静的ファイルの出力オプション
  extract_css: false

  # 開発・テスト・本番環境でのアセットのホストを指定できます
  # Example: https://assets.example.com
  # asset_host: 

  # 開発とテスト環境用の webpack-dev-server の設定
  # 開発環境でのファイル変更を監視し、ホットリロードを行います
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    # 開発サーバーを自動で再起動する設定
    reload_manifest: true
    quiet: false
    compress: true

development:
  <<: *default
  compile: true # 開発環境では自動コンパイルを有効化

test:
  <<: *default
  compile: true # テスト環境でも自動コンパイルを有効化
  # CSS抽出を無効にする（必要に応じて設定）
  extract_css: false

production:
  <<: *default
  compile: false # 本番環境では事前コンパイルを推奨
  extract_css: true # CSSを抽出して独立したファイルとして出力
  cache_manifest: true # manifest.jsonをキャッシュしてパフォーマンス向上
